-- Create tenant_applications table
CREATE TABLE IF NOT EXISTS `tenant_applications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL,
  `property_id` int(11) NOT NULL,
  `unit_id` int(11) DEFAULT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `date_of_birth` date DEFAULT NULL,
  `nationality` varchar(100) DEFAULT NULL,
  `occupation` varchar(100) DEFAULT NULL,
  `employer` varchar(255) DEFAULT NULL,
  `monthly_income` decimal(10,2) DEFAULT NULL,
  `id_type` enum('nin','passport','drivers_license','voters_card','international_passport') DEFAULT 'nin',
  `id_number` varchar(100) DEFAULT NULL,
  `id_document` varchar(255) DEFAULT NULL,
  `emergency_contact_name` varchar(255) DEFAULT NULL,
  `emergency_contact_phone` varchar(50) DEFAULT NULL,
  `emergency_contact_relationship` varchar(100) DEFAULT NULL,
  `previous_landlord` varchar(255) DEFAULT NULL,
  `previous_landlord_phone` varchar(50) DEFAULT NULL,
  `reason_for_leaving` text DEFAULT NULL,
  `proposed_move_in_date` date DEFAULT NULL,
  `lease_duration_months` int(3) DEFAULT 12,
  `status` enum('pending','under_review','approved','rejected','withdrawn') DEFAULT 'pending',
  `review_notes` text DEFAULT NULL,
  `reviewed_by` int(11) DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `application_fee` decimal(10,2) DEFAULT 0.00,
  `application_fee_paid` tinyint(1) DEFAULT 0,
  `documents` json DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_applications_admin_id_index` (`admin_id`),
  KEY `tenant_applications_property_id_index` (`property_id`),
  KEY `tenant_applications_unit_id_index` (`unit_id`),
  KEY `tenant_applications_status_index` (`status`),
  KEY `tenant_applications_created_at_index` (`created_at`),
  KEY `tenant_applications_deleted_at_index` (`deleted_at`),
  CONSTRAINT `tenant_applications_admin_id_foreign` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tenant_applications_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tenant_applications_unit_id_foreign` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
